#!/bin/bash
#
# Script to monitor PowerDNS performance
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#%# family=auto
#%# capabilities=autoconf

PDNS_CONTROL="${pdns_control:-/usr/local/bin/pdns_control}"

if [ "$1" = "autoconf" ]; then
        if [ -e "$PDNS_CONTROL" ]; then
                echo yes
                exit 0
        else
                echo no
                exit 1
        fi
fi

if [ "$1" = "config" ]; then
        echo 'graph_title PDNS Auth. queries'
        echo 'graph_args -l 0 --base 1000'
        echo 'graph_vlabel numbers of'
        echo 'graph_category PDNS Authoritative'
        echo 'graph_info This graph shows Power DNS performance on the machine.'
        echo 'recursing_answers.label recursing answers'
        echo 'recursing_answers.type DERIVE'
        echo 'recursing_answers.min 0'
        echo 'recursing_answers.info Number of recursive answers sent out'
        echo 'recursing_questions.label recursing queries'
        echo 'recursing_questions.type DERIVE'
        echo 'recursing_questions.min 0'
        echo 'recursing_questions.info Number of queries sent to recursor'
        echo 'tcp_answers.label tcp answers'
        echo 'tcp_answers.type DERIVE'
        echo 'tcp_answers.min 0'
        echo 'tcp_answers.info Number of answers sent out over TCP'
        echo 'tcp_queries.label tcp queries'
        echo 'tcp_queries.type DERIVE'
        echo 'tcp_queries.min 0'
        echo 'tcp_queries.info Number of TCP queries received'
        echo 'udp_answers.label udp answers'
        echo 'udp_answers.type DERIVE'
        echo 'udp_answers.min 0'
        echo 'udp_answers.info Number of answers sent out over UDP'
        echo 'udp_queries.label udp queries'
        echo 'udp_queries.type DERIVE'
        echo 'udp_queries.min 0'
        echo 'udp_queries.info Number of UDP queries received'
        exit 0
fi

echo recursing_answers.value `$PDNS_CONTROL show recursing-answers`
echo recursing_questions.value `$PDNS_CONTROL show recursing-questions`
echo tcp_answers.value `$PDNS_CONTROL show tcp-answers`
echo tcp_queries.value `$PDNS_CONTROL show tcp-queries`
echo udp_answers.value `$PDNS_CONTROL show udp-answers`
echo udp_queries.value `$PDNS_CONTROL show udp-queries`