#!/bin/bash
#
# Script to monitor PowerDNS performance
#
# Parameters understood:
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#%# family=auto
#%# capabilities=autoconf

PDNS_CONTROL="${pdns_control:-/usr/local/bin/pdns_control}"

if [ "$1" = "autoconf" ]; then
        if [ -e "$PDNS_CONTROL" ]; then
                echo yes
                exit 0
        else
                echo no
                exit 1
        fi
fi

if [ "$1" = "config" ]; then
        echo 'graph_title PDNS Auth. latency'
        echo 'graph_args -l 0'
        echo 'graph_vlabel usec'
        echo 'graph_category PDNS Authoritative'
        echo 'graph_info This graph shows Power DNS latency on the machine.'
        echo 'latency.label latency'
        echo 'latency.info Average number of microseconds needed to answer a question'
        echo 'latency.type GAUGE'
        exit 0
fi




echo "latency.value $($PDNS_CONTROL show latency | awk -F= '{print $2}')"
