#!/bin/sh
#
#  pdns_recursor munin plugin.
#  Written by Sean Reifschneider <jafo@tummy.com> 2009-12-03
#  Placed in the public domain
#
#  Requires running as root:
#
#    echo '[pdns_rec_*]' >/etc/munin/plugin-conf.d/pdns_rec
#    echo 'user root' >>/etc/munin/plugin-conf.d/pdns_rec

REC_CONTROL="${rec_control:-/usr/local/bin/rec_control}"

if [ "$1" = "autoconf" ]; then
        if [ -e "$REC_CONTROL" ]; then
                echo yes
                exit 0
        else
                echo no
                exit 1
        fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title PDNS Recursor Throttling'
	echo 'graph_order throttled'
	echo 'graph_vlabel queries'
	echo 'graph_info Throttled queries'
	echo 'graph_category PDNS Recursor'

	echo 'throttled.label throttled'
	echo 'throttled.min 0'
	echo 'throttled.type COUNTER'
	echo 'throttled.info Throttled queries'

	exit 0
fi

echo throttled.value `$REC_CONTROL get throttled-out`

exit 0
